name: PHP OSM Tiles Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    name: "php-osm-tiles build - PHP ${{ matrix.php-versions }}"

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Lint PHP Sources
        run: composer run-script ci:lint

      - name: PHP Code Sniffer
        run: composer run-script ci:phpcs

      - name: Static Analysis
        run: composer run-script ci:phpstan

      - name: Unit Tests
        run: composer run-script ci:tests
